### ISSUE TITLE
Get current index from controller

### ISSUE THREAD

**Issue by Tukhtamurodov-Sardorbek** [theiskaa/widget_slider#2]
It's not possible to determine the current index through SliderController, please add this feature...

**Comment by theiskaa** [comment]
Hi @Tukhtamurodov-Sardorbek first of all, thanks for your interest!
Actually, it's possible to do. You just have to follow steps that I've mentioned down below

---

1. **Create a local index on your widget state.**
```dart
int currentIndex = 0;
```

2. **Then update it on each move:**
```dart
WidgetSlider(
  ...
  onMove: (int index) {
    setState(() => activeIndex = index);
  }
```

**Comment by Tukhtamurodov-Sardorbek** [comment]
> 

Thanks for the answer!
